language: python

services:
  - redis-server

python:
  - "2.7"
  - "3.4"

env:
    - DJANGO=1.8.2
    - DJANGO=1.7.8

install:
  - pip install -q django==$DJANGO
  - pip install -r requirements.txt
  - pip install pytest-django pytz coveralls
  - python setup.py install

script:
  - coverage run --source=django_q setup.py test

after_success:
  - coveralls
