language: python

services:
  - redis-server

python:
  - "2.7"
  - "3.4"

env:
    - DJANGO=1.8.3
    - DJANGO=1.7.9

install:
  - pip install -q django==$DJANGO
  - pip install -r requirements.txt
  - pip install pytest-django coveralls sphinx
  - python setup.py install

script:
  - coverage run --source=django_q -m py.test
  - sphinx-build -nW -c docs/conf.py

after_success:
  - coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cbcff78c4be241602332
    on_success: change
    on_failure: always
    on_start: never
